speakerName: Jochen Schalanda
year: 2017

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    bindHost: 127.0.0.1
    port: 8080

swagger:
  resourcePackage: com.example.demo.resource
