= Dropwizard Demo Application

* Build project:

  ./gradlew build

* Build UberJAR:

  ./gradlew shadowJar

* Start application:

  ./gradlew run


== Examples

=== Frontend

* Show Swagger UI with all HTTP endpoints: http://127.0.0.1:8080/swagger

* Show ping-pong:

  curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/ping?message=pong'

* Show Kittens:

  curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/kittens'

* Show "Findus":

  curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/kittens/Findus'

* Show HTTP 404 from `Optional<Kitten>`:

  curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/kittens/Carlo'

* Create new Kittens:

  curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \
     "id": 1, \
     "name": "Tom", \
     "type": "CUTE" \
   }' 'http://127.0.0.1:8080/kittens'


  curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \
      "id": 2, \
      "name": "Garfield", \
      "type": "FLUFFY" \
   }' 'http://127.0.0.1:8080/kittens'

  curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \
      "id": 3, \
      "name": "Grumpy", \
      "type": "GRUMPY" \
   }' 'http://127.0.0.1:8080/kittens'

* Show created Kittens:

  curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/kittens/Garfield/view'

* Show rendering of HTML page in web browser: http://127.0.0.1:8080/kittens/Grumpy/view


=== Admin Backend

* Show metrics: http://127.0.0.1:8080/admin/metrics?pretty=true
* Show thread status: http://127.0.0.1:8080/admin/threads
* Show health checks: http://127.0.0.1:8080/admin/healthcheck?pretty=true
* Toggle status of DemoHealthCheck:

  curl -X POST http://127.0.0.1:8080/admin/tasks/toggle-health


=== Backend (CLI)

* Show `GreetingCommand`:

  java -jar build/libs/demo-1.0.0-SNAPSHOT-all.jar greet config.yml

* Show configuration check:

  java -jar build/libs/demo-1.0.0-SNAPSHOT-all.jar check config.yml


== License

Copyright (C) 2016 Jochen Schalanda

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0